### ISSUE TITLE
add a sign in log in page

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia#19]
add a sign-in log-in page and function it with the navbar's profile and log-out button.

**Comment by oxone-999** [comment]
@samratghosh291 please assign it to me

**Comment by samratghosh291** [comment]
Thank you for your interest ❤️
Happy Coding !!

**Comment by oxone-999** [comment]
Can i change your codebase to MERN STACK, in that case I can make it more efficient, more better design and more robust, and then you can also assign me new PRs with hacktoberfest tags and I can make those changes also.

**Comment by oxone-999** [comment]
I can literally solve all your issues, I have a very good experience in web development.
