### ISSUE TITLE
No favicon icon on the website

### ISSUE THREAD

**Issue by SumitVerma-coder** [samratghosh291/Musicia#31]
Currently there is no favicon icon present on the website
![image](https://github.com/samratghosh291/Musicia/assets/112965155/f06f0f2f-7945-4eee-872c-e3d6183bd756)
**_PLEASE ASSIGN ME THIS ISSUE UNDER HACTOBERFEST TAG_**

**Comment by samratghosh291** [comment]
Thank you for your interest.❤️
Happy coding 🚀

**Comment by Aamir-Manzoor** [comment]
hey! can i work on this its been 2 days.

**Comment by Aamir-Manzoor** [comment]
No updates on this issue

**Comment by vivek33up** [comment]
Could you take a look at my PR and accept it, if it looks good. Thanks!
