### ISSUE TITLE
Fix needed: Music pause functionality and responsive layout for mobiles and tablets

### ISSUE THREAD

**Issue by Avinash-31** [samratghosh291/Musicia#32]

**Comment by Avinash-31** [comment]
Hey ...
Can u assign me with this issue . I will fix the bug for pausing music and make the website resposive

**Comment by samratghosh291** [comment]
Thank you for your interest.
Happy Coding 🚀

**Comment by Avinash-31** [comment]
Done have a check...sent the pr
