### ISSUE TITLE
remove times lap from songs bar

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia#36]
remove this unnecessary times lap from main container align the rest of the things properly

![Screenshot (83)](https://github.com/samratghosh291/Musicia/assets/101434286/e92af49d-e605-4d63-99a1-d7927f147f6d)

**Comment by Judge-Paul** [comment]
@samratghosh291 Can I work on this?

**Comment by samratghosh291** [comment]
No @Judge-Paul you cannot work on it as akashpambhar already assigned in it.
You can raise another issue and asking for assigning.
