### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia#41]
You should do this task.
- The tech stack in readme.md is not in the right place.
- Complete write the installation process.

1.   star⭐ the repo
2.  fork the repo
3. make a clone using this command `git clone https://github.com/samratghosh291/Musicia.git`.
then you can make changes.

**Comment by jfmartinz** [comment]
Please assign it to me. Thanks

**Comment by samratghosh291** [comment]
Thank you for your interest.
Happy Coding ❤️

**Comment by jfmartinz** [comment]
Should I add creating branch, pushing changes, comming instructiosn??

**Comment by samratghosh291** [comment]
Yes you create this details also...

1. 1st raise an issue.
2. Then asking project maintainer to assigning you in this issue.
3. After assign successful you can going forward for contribution. 
Mention the above before forking the project.

And also mention the 
1. Make a new branch 
2. Git add
3. Git commit 
4. Git pull 
5. Git push 
6. Make pr 
7. Wait for the code reviewer
8. Never do spamming
