### ISSUE TITLE
signin-login page is not working

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia#43]
in the navbar sign-in and login button is not working properly. whether inside the pages directory, there is a sign-in.html and login.html page is there.

**Comment by seog-jun** [comment]
Can I give it a shot?

**Comment by samratghosh291** [comment]
Thank you for your contribution. 
Happy Coding ❤️

**Comment by seog-jun** [comment]
Just wanna make sure that which one is login button, I'm seeing there are two buttons and it seems like not clear for me.
![image](https://github.com/samratghosh291/Musicia/assets/88434287/dba9011c-3469-4d02-8209-56ac68d3de1e)

**Comment by samratghosh291** [comment]
1st one is loging button and 2nd one is logout.. you cange it by yourself

**Comment by seog-jun** [comment]
Okay, then where is sign-in button?
