### ISSUE TITLE
my songs button is not working

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia#44]
in navbar my songs button is not working whether inside assets button there are files available for listed all the songs.
also make sure when someone visited my songs page it will paly the current song in background.

**Comment by seog-jun** [comment]
Can I give it a shot?

**Comment by NsCracker** [comment]
@samratghosh291 May I proceed with this?

**Comment by seog-jun** [comment]
Oh I've been doing that, I forgot to leave a comment..

**Comment by NsCracker** [comment]
@seog-jun I'm almost done with this.

**Comment by seog-jun** [comment]
Alright, go ahead.

**Comment by samratghosh291** [comment]
@NsCracker and @seog-jun when you are doing an open source contribution you should wait for assigning you in this project by maintainer.
Then you should go for changing.
I wish from next time you will remember that.
But thank you for your contribution.

**Comment by samratghosh291** [comment]
And the assigning process would be done first come first serve basis.

**Comment by NsCracker** [comment]
@samratghosh291, this was my first time contributing to open source. Next time, I'll remember to get the project assigned by the maintainer.
Thanks for merging👍🏻
