### ISSUE TITLE
[BUG] In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.

### ISSUE THREAD

**Issue by gauravsingh1281** [samratghosh291/Musicia#49]
**Screenshot**

<img width="960" alt="Screenshot 2023-10-07 233815" src="https://github.com/samratghosh291/Musicia/assets/85905403/c6644950-a1f2-4ab8-b518-7418c358e3bb">

<img width="960" alt="Screenshot 2023-10-07 233925" src="https://github.com/samratghosh291/Musicia/assets/85905403/6744e0e2-7fea-475d-ae85-81a8e051c14a">

--------------------

@samratghosh291 Right now, the copyright year is written manually, which means someone has to change it whenever a new year begins. However, with just a few lines of code in JavaScript, we can make it automatic. This means that the copyright year will always be up-to-date without anyone having to change it manually. For example, if the current year is 2023, the copyright section will show 2023. And when the year changes to 2024, the copyright section will automatically update to 2024.

**Comment by gauravsingh1281** [comment]
@samratghosh291 Please assign this issue to me under hacktoberfest label.

**Comment by samratghosh291** [comment]
Thank you @gauravsingh1281 for your interest. 
Happy Coding ❤️
