### ISSUE TITLE
Make footer

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia#5]
Make a beautiful footer as it looks beautiful

**Comment by samratghosh291** [comment]
Go to [https://in.pinterest.com/pin/36028865761543096#imgViewer](url)
Clone it.

**Comment by samratghosh291** [comment]
@Baburao-sanivada Thank you for your interest. Happy Coding ❤️

**Comment by Chitresh-code** [comment]
Hey @samratghosh291 if the issue is still available please assign it to me.

**Comment by Baburao-sanivada** [comment]
Hi @samratghosh291 there is Already a footer present out there
Can I Know How exactly the Footer Should Look Like?
