### ISSUE TITLE
Add dark theme 

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia#50]
Add the dark theme with a suitable icon switch and also make it impressive.
Also attach a ss of post improvement and raise a pr.

**Comment by priyanshu-buwade** [comment]
Hey Samarth,

I can work on adding dark mode to the player.

**Comment by priyanshu-gupta0503** [comment]
hey @samratghosh291  i would like to contribute on this.
I feel myself suitable because my previous project was also on theme building.

**Comment by samratghosh291** [comment]
@priyanshu-buwade go for it 🚀

**Comment by samratghosh291** [comment]
Assigning for a issue is basis on first come first serve. 
You can raise a new issue and asking for assigning. 
Thank you for your interest ☺️
