### ISSUE TITLE
fix the main song div size

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia#57]
the centered div is not fixed. it is changing as per the song's name. so that the previous, next, and play/pause button is not in a fixed position.

![Screenshot (87)](https://github.com/samratghosh291/Musicia/assets/101434286/a779a077-8a22-46af-8d34-901dcfad7983)
 fix this one.

**Comment by ezhillragesh** [comment]
Hi @samratghosh291  ,

Is it possible to assign this issue to me? I believe I can help in addressing the problem and working towards a solution. 

Looking forward to your response.

Best regards,
Ezhill Ragesh

**Comment by priyanshu-buwade** [comment]
I have fixed this issue in my recent PR #58 .

![Screenshot (215)](https://github.com/samratghosh291/Musicia/assets/105071181/ebacae50-4dcf-4498-ba2c-058b7b1d1555)

**Comment by samratghosh291** [comment]
@ezhillragesh  i happy to see your interest. 
But we have been assigning the issues on first come first serve basis.
So it is not possible to assign you in this issue but you can raise another new issue and asking for assigning you.
Thank you.
