### ISSUE TITLE
Add Time Stamp (Audio Length) in the list of songs in "My Songs" page.

### ISSUE THREAD

**Issue by priyanshu-buwade** [samratghosh291/Musicia#60]
The length of songs is not shown there in the My Songs page,
Please Assign me this issue so I can fix this - 

![Screenshot (217)](https://github.com/samratghosh291/Musicia/assets/105071181/254d68b6-45a4-4fcc-9e77-c161a9ae7629)

**Comment by samratghosh291** [comment]
OK thank you for your interest ☺️ 
Happy Coding 🚀
