### ISSUE TITLE
Enhancement of sign up page

### ISSUE THREAD

**Issue by TheCoderAdi** [samratghosh291/Musicia#66]
![image](https://github.com/samratghosh291/Musicia/assets/111285422/b48f2d47-acb9-4c6d-88b0-049cb52a91c6)
As you can see in the sign up page the title is Document and in the input box of username and email the icons are missing.

**Comment by priyanshu-gupta0503** [comment]
hey@samratghosh291 @TheCoderAdi  I would like to work on this project pls assign it to me with hacktober fest label

**Comment by TheCoderAdi** [comment]
Hey @priyanshu-gupta0503 I have already done that part, find any other issues

**Comment by priyanshu-gupta0503** [comment]
ok
