### ISSUE TITLE
Bug: Signup page not show submit button

### ISSUE THREAD

**Issue by abhishek-kumar-91** [samratghosh291/Musicia#71]
When will you come to signup page  then show the all input tag but not show submit button. 
Button is hide in div box 
![Screenshot (100)](https://github.com/samratghosh291/Musicia/assets/111195553/6245139e-3639-4fb2-b212-34c03ae8a653)

**Comment by Jai-Marothiya** [comment]
Hi @samratghosh291, 

Please assign this issue to me. I can fix this issue.

Thanks

**Comment by abhishek-kumar-91** [comment]
@samratghosh291, check this pr and merge that
Fixes #71

**Comment by draunger** [comment]
Assign me
