### ISSUE TITLE
Key board connectivity

### ISSUE THREAD

**Issue by youtanimstar** [samratghosh291/Musicia#74]
On this website, we cannot play or pause the music by pressing the keyboard button. For example, in YouTube music or Spotify, we can see some keyboard connectivity so that we can easily play or pause by pressing the keyboard buttons. But on this website every time we have to click the play buttons. I think this keyboard connectivity needs to be implemented.

![Screenshot from 2023-10-13 19-29-02](https://github.com/samratghosh291/Musicia/assets/107903218/e74a1b0c-d2df-4b8e-aac6-89ce83c28021)

Can you please assign this work to me !!

**Comment by samratghosh291** [comment]
Yes. go for it.
Happy coding🚀
