### ISSUE TITLE
Login page enhancement

### ISSUE THREAD

**Issue by TheCoderAdi** [samratghosh291/Musicia#91]
There is no icon for the email 
![image](https://github.com/samratghosh291/Musicia/assets/111285422/8b0c106b-096b-458b-beef-f7f374ee2d69)

**Comment by sukuasoft** [comment]
@TheCoderAdi  
Can I work on this issue

**Comment by TheCoderAdi** [comment]
Hey @sukuasoft 
I have already fix that issue, you can search for other issues
