### ISSUE TITLE
Nav bar items do not align properly

### ISSUE THREAD

**Issue by divyansh14kr** [samratghosh291/Musicia#96]
the login and the logout button overflow from the navbar.
also would like to suggest to move them to the right side for better user experience
<img width="1440" alt="Screenshot 2023-10-24 at 10 52 28 AM" src="https://github.com/samratghosh291/Musicia/assets/118956824/84634537-35f7-4840-90e2-e35d0e857cbf">

**Comment by samratghosh291** [comment]
go for it...!!!
